### DISCUSSION TITLE
我想问下这个怎么设置多个模板？

### DISCUSSION THREAD

**Discussion by chenxuyuanchen** [timonwong/prometheus-webhook-dingtalk#209] [Q&A] [answered]
我有几个钉钉机器人。一个机器人用一个模板。另外一个机器人用另外一个模板
![image](https://user-images.githubusercontent.com/93701704/210043794-ec8ee9a6-7b63-4621-a192-804db487e4fd.png)
这里只能设置一个模板地址

**Comment by timonwong** [comment]
模板可以有多个，templates 里面的作用是 define 模板，如果有同名的 define，当然最后结果看起来就只有一个，但是如果你有:
- a.tmpl
- b.tmpl
两个模板不同的 define，比如

```
{{ define "abc1.content }}
XXXXXXXXXXX
{{ end }}
```

```
{{ define "abc2.content" }}
{{ end }}
```

然后在 targets 中引用:

```yaml
targets:
   target_abc1:
     url: xxxxxxx
     message:
       text: '{{ template "abc1.content" . }}'
   target_abc2:
     url: xxxx
     message:
       text: '{{ template "abc2.content" . }}'
```

**Reply by chenxuyuanchen** [reply]
非常感谢作者的回复👍，对我很有帮助。我以为会很久才会回复我，还是自己对于go语言不了解。我的模板也有点问题😂

**Comment by timonwong** [comment, marked as answer]
当然为了简单，甚至也可以不使用 templates 指定文件，直接内联模板也可以，比如

```yaml
targets:
   target_abc1:
     url: xxxxxxx
     message:
       text: 'Hello, this is text abc1'
   target_abc2:
     url: xxxx
     message:
       text: 'Hello, this is text abc2'
````

**Comment by timonwong** [comment]
当然为了简单，甚至也可以不使用 templates 指定文件，直接内联模板也可以，比如

```yaml
targets:
   target_abc1:
     url: xxxxxxx
     message:
       text: 'Hello, this is text abc1'
   target_abc2:
     url: xxxx
     message:
       text: 'Hello, this is text abc2'
````
