### ISSUE TITLE
unexpected status code 404

### ISSUE THREAD

**Issue by kerven88** [timonwong/prometheus-webhook-dingtalk#106]
alertmanager配置了dingtalk地址后，日志看到请求404，请问这个是什么原因？

![image](https://user-images.githubusercontent.com/51351006/84144275-96c62c00-aa8a-11ea-9c7c-62428994aef5.png)

**Comment by is-a-gamer** [comment]
在配置文件中这样配置
prometheus-webhook-dingtalk.yml
```yaml
targets:
  webhook:
    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
template: dingtalk-message.tmpl
```
启动prometheus-webhook-dingtalk加上参数
```shell
/usr/local/bin/prometheus-webhook-dingtalk --config.file=prometheus-webhook-dingtalk/prometheus-webhook-dingtalk.yml --web.enable-lifecycle
```
之后你应该可以在日志中看到
```shell
Jun 10 09:47:11 192-168-1-xxx prometheus-webhook-dingtalk[20176]: level=info ts=2020-06-10T01:47:11.122Z caller=main.go:117 component=configuration msg="Loading templates" templates=/etc/prometheus-webhook-dingtal component=configuration msg="Loading templates" templates=templates/dingtalk-message.tmpl

Jun 10 09:47:11 192-168-1-xxx prometheus-webhook-dingtalk[20176]: ts=2020-06-10T01:47:11.124Z caller=main.go:133 component=configuration msg="Webhook urls for prometheus alertmanager" urls=http://localhost:8060/dingtalk/webhook/send
```
