### ISSUE TITLE
使用secret挂载默认的config.yml报错

### ISSUE THREAD

**Issue by oldthreefeng** [timonwong/prometheus-webhook-dingtalk#118]
使用yaml如下. 在`dockerfile`里面使用的配置文件是`/etc/prometheus-webhook-dingtalk/config.yml`
```
cat deploy.yaml
...
          volumeMounts:
            - mountPath: /etc/prometheus-webhook-dingtalk/config.yml
              name: cm
              subPath: config.yml
...
      volumes:
        - name: cm
          secret:
            defaultMode: 420
            items:
              - key: config.yml
                path: config.yml
            secretName: dingidng-webhook-config

kubectl app -f  deploy.yaml
```
查看日志
```
.....
level=info ts=2020-09-22T08:15:22.873Z caller=coordinator.go:89 component=configuration file=config.yml msg="Loading configuration file"
level=error ts=2020-09-22T08:15:22.873Z caller=coordinator.go:91 component=configuration file=config.yml msg="Loading configuration file failed" err="open config.yml: no such file or directory"
```

然后换成自己写的就好了.很奇怪为什么是这样的. 

```
        - args:
            - '--web.listen-address=:5000'
            - '--config.file=/config.yml'
          volumeMounts:
            - mountPath: /config.yml
              name: cm
              subPath: config.yml
...
      volumes:
        - name: cm
          secret:
            defaultMode: 420
            items:
              - key: config.yml
                path: config.yml
            secretName: dingidng-webhook-config
```
