### ISSUE TITLE
更新配置文件失败

### ISSUE THREAD

**Issue by DesireWithin** [timonwong/prometheus-webhook-dingtalk#203]
我尝试指定单个webhook的message内容, 根据README:
https://github.com/timonwong/prometheus-webhook-dingtalk/blob/589d858c1f7c9409a67146d8c14e28a208bf34e7/README.md?plain=1#L95-L98

我的配置文件如下：
```yaml
## Request timeout
timeout: 5s

## Customizable templates path
templates:
  - /etc/dingtalk/template.tmpl

## You can also override default template using `default_message`
## The following example to use the 'legacy' template from v0.3.0
#default_message:
#  title: {{ template "legacy.title" . }}
#  text: {{ template "legacy.content" . }}

## Targets, previously was known as "profiles"
targets:
  webhook_dingtalk:
    url: https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXXXX
    secret: XXXXXXXXXX
  message:
    title: '{{ .CommonLabels.alertname }}'
    text: '{{ .CommonLabels.alertname }}'
```
当我尝试`curl -XPOST http://prometheus-webhook-dingtalk.XXX.XXX/-/reload`，返回错误：
```
failed to reload config: yaml: unmarshal errors:
  line 20: field title not found in type config.plain
  line 21: field text not found in type config.plain
```

prometheus-webhook-dingtalk version: v2.1.0
