### ISSUE TITLE
Loading env variables on config.yml

### ISSUE THREAD

**Issue by Corfucinas** [timonwong/prometheus-webhook-dingtalk#208]
Can you enable a feature to load .env variables in the config.yml file?

```yml
## Targets, previously was known as "profiles"
targets:
  webhook1:
    url: https://oapi.dingtalk.com/robot/send?access_token=${DINGTALK_ALERT_TOKEN} # the token it's on .env
    # secret for signature
    secret: ${DINGTALK_SECRET} # the secret is under .env
    mention:
      all: true
```

The variables can be passed to the docker container under `environment` and be available inside the container for substitution.
