### ISSUE TITLE
是否支持同时向多个钉钉群发送报警

### ISSUE THREAD

**Issue by crazyacking** [timonwong/prometheus-webhook-dingtalk#21]
我将prometheus-webhook-dingtalk镜像部署到k8s集群，并使用容器启动参数来配置dingtalk_url，配置如下：
```
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-webhook-dingtalk
  template:
    metadata:
      labels:
        app: prometheus-webhook-dingtalk
    spec:
      containers:
      - image: {{ .Values.image.repository }}/prometheus-webhook-dingtalk:v0.3.0
        name: prometheus-webhook-dingtalk
        args:
        - "--ding.profile=node=https://oapi.dingtalk.com/robot/send?access_token=d428ffd248ab55551db6f485ab49a03f7f73025d17f8cebdeys39783ac5416d3"
        - "--web.listen-address=:8060"
```
我用`--ding.profile=node=xxx`来指定dingtalk_url参数，我的问题是：
- 如何指定多个dingtalk_url，向多个钉钉群发送报警？
