### ISSUE TITLE
prometheus-webhook-dingtalk告警内容解析失败

### ISSUE THREAD

**Issue by duhongx** [timonwong/prometheus-webhook-dingtalk#211]
prometheus-webhook-dingtalk启动后告警内容解析失败，出错日志如下所示：
prometheus-webhook-dingtalk[20405]: ts=2023-01-01T14:11:20.066Z caller=dingtalk.go:82 level=error component=web target=webhook1 msg="Cannot decode prometheus webhook JSON request" err="json: cannot unmarshal array into Go value of type models.WebhookMessage"
prometheus的版本为：quay.io/prometheus/prometheus:v2.36.1
alertmanager的版本为：quay.io/prometheus/alertmanager:v0.24.0

**Comment by duhongx** [comment]
使用的prometheus-webhook-dingtalk的包为prometheus-webhook-dingtalk-2.1.0.linux-amd64

**Comment by timonwong** [comment]
不知道你把该程序暴露的 url 配置到哪儿去了，不是在 alertmanager 里么?

alertmanager receiver 配置
```yaml
receivers:
- name: xxxx
  webhook_configs:
  - url: <address to prometheus webhook dingtalk target>
```

**Comment by duhongx** [comment]
您好，alertmanager配置的是prometheus-webhook-dingtalk的地址，配置文件内容如下：
```
  webhook_configs:
  - send_resolved: true
    url: http://10.10.8.50:8060/dingtalk/webhook1/send
- name: monitoring/dinghook/Default
  webhook_configs:
  - send_resolved: true
    url: http://10.10.8.50:8060/dingtalk/webhook1/send
```
从k8s的node节点测试网络是通的
```
[root@k8s-1 ~]# curl http://10.10.8.50:8060/dingtalk/webhook1/send -I
HTTP/1.1 405 Method Not Allowed
Date: Tue, 03 Jan 2023 06:39:30 GMT
[root@k8s-1 ~]# telnet 10.10.8.50 8060
Trying 10.10.8.50...
Connected to 10.10.8.50.
Escape character is '^]'.
```
在prometheus-webhook-dingtalk的部署服务器上查看服务正常运行，端口开放也正常
```
[root@deploy ~]# ps -ef|grep prometheus-webhook-dingtalk
root       20405       1  0 1月01 ?       00:00:02 /usr/local/bin/prometheus-webhook-dingtalk/prometheus-webhook-dingtalk --web.enable-ui --web.enable-lifecycle --config.file=/usr/local/bin/prometheus-webhook-dingtalk/config.yml
root       74488   74396  0 14:33 pts/1    00:00:00 grep --color=auto prometheus-webhook-dingtalk
[root@deploy ~]# ss -tnlp|grep 20405
LISTEN 0      4096                    *:8060             *:*    users:(("prometheus-webh",pid=20405,fd=3))   
```
