### ISSUE TITLE
docker 部署支持 healthy 健康检查吗？

### ISSUE THREAD

**Issue by YaoJusheng** [timonwong/prometheus-webhook-dingtalk#218]
我打算将alertmanager、prometheus等工具和dingtalk一起用compose编排，那么在compose文件中，怎么对dingtalk做healthcheck呢，该镜像没有shell，无法安装curl等工具，除了自己写dockerfile通过源码编译，还有别的解决方法吗？

**Comment by timonwong** [comment]
## 1.3.0 / 2019-12-09

- [FEATURE/ENHANCEMENT] Improved compatibility: Now the following v0.3.0 command line flags are supported as well: `--ding.profile`, `--ding.timeout` and `--template.file`. #72
- [FEATURE/ENHANCEMENT] Add support to reload through API `/-/reload` (Disabled by default, can be enabled via the `--web.enable-lifecycle` flag). #70
- [FEATURE/ENHANCEMENT] Add ready and health check API endpoint: `/-/healthy` and `/-/ready`. #71
- [CHANGE] (Backward compatible) Rename `--web.ui-enabled` to `--web.enable-ui`.

**Comment by YaoJusheng** [comment]
这似乎并不是我所问的问题答案, 如果你的回答是指提供了/-/healthy接口,用于外部请求的健康检查,这我知道,
但我想在compose部署时就能看到它的状态, compose内写入的内容样式如下:
```yaml
dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:v1.3.0
    container_name: ${COMPOSE_PROJECT_NAME}_dingtalk
    healthcheck:
      test: [CMD, curl, -f, localhost:8060/-/healthy]
      interval: 30s
      timeout: 5s
      retries: 3
    # ...
```
运行之后,一直显示状态为unhealthy, 原因应该是busybox镜像没有curl命令, 也无法安装,是否有别的检查方式呢? netstat、lsof这些只能通过端口或进程查询.

> ## 1.3.0 / 2019-12-09
> * [FEATURE/ENHANCEMENT] Improved compatibility: Now the following v0.3.0 command line flags are supported as well: `--ding.profile`, `--ding.timeout` and `--template.file`. [Compatible with v0.3.0 command line flags #72](https://github.com/timonwong/prometheus-webhook-dingtalk/pull/72)
> * [FEATURE/ENHANCEMENT] Add support to reload through API `/-/reload` (Disabled by default, can be enabled via the `--web.enable-lifecycle` flag). [Allow reload through API #70](https://github.com/timonwong/prometheus-webhook-dingtalk/pull/70)
> * [FEATURE/ENHANCEMENT] Add ready and health check API endpoint: `/-/healthy` and `/-/ready`. [Add HTTP ready and healthy handler #71](https://github.com/timonwong/prometheus-webhook-dingtalk/pull/71)
> * [CHANGE] (Backward compatible) Rename `--web.ui-enabled` to `--web.enable-ui`.
