### ISSUE TITLE
为啥提示找不到模板？

### ISSUE THREAD

**Issue by sanger89** [timonwong/prometheus-webhook-dingtalk#36]
### pod日志
然后我修改了webhook-dingtalk.yml运行时的arg参数，原来是没有template.file这一项的，加了后提示找不到这个文件

```
[root@kube-master-237 system]# kubectl logs -n monitoring webhook-dingtalk-c74bbbff4-wz2pm 
level=info ts=2019-07-04T01:21:50.392206461Z caller=main.go:37 msg="Starting prometheus-webhook-dingtalk" version=
level=error ts=2019-07-04T01:21:50.392355553Z caller=main.go:45 filename="\"/usr/share/prometheus-webhook-dingtalksr/share/prometheus-webhook-dingtalk/template/default.tmpl\": no such file or directory"
```

### pod 模板文件
但是我回退deployment后进入pod查看这个文件是存在的，并且已经修改成功了，权限位也没问题呀  可读啊
```
/ # ls -l /usr/share/prometheus-webhook-dingtalk/template/default.tmpl 
-rw-r--r--    1 root     root           978 Jul  3 13:36 /usr/share/prometheus-webhook-dingtalk/template/default.tmpl
```

### webhook-dingtalk    deployment
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: dingtalk
  name: webhook-dingtalk
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dingtalk
    spec:
      containers:
      - name: dingtalk
#        image: timonwong/prometheus-webhook-dingtalk:v0.3.0
        image: sanger/prometheus-webhook-dingtalk:v0.0.1
        imagePullPolicy: IfNotPresent
        # 设置钉钉群聊自定义机器人后，使用实际 access_token 替换下面 xxxxxx部分
        args:
          - --template.file="/usr/share/prometheus-webhook-dingtalk/template/default.tmpl"          
          - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxx
        ports:
        - containerPort: 8060
          protocol: TCP

```
