### ISSUE TITLE
钉某人无效

### ISSUE THREAD

**Issue by CoolTomato** [timonwong/prometheus-webhook-dingtalk#85]
```
webhook_mention_all:
    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
    secret: SEC000000000000000000000
    mention:
      all: true
```
配置完并没有@效果，access_token、secret改成我自己的了
