### ISSUE TITLE
respCode=300001 respMsg="token is not exist"

### ISSUE THREAD

**Issue by 7error** [timonwong/prometheus-webhook-dingtalk#91]
```shell
level=error ts=2020-03-30T03:57:11.868Z caller=dingtalk.go:103 component=web target=webhook1 msg="Failed to send notification to DingTalk" respCode=300001 respMsg="token is not exist"
```

**Comment by timonwong** [comment]
```yaml
## Targets, previously was known as "profiles"
targets:
  webhook1:
    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
    # secret for signature
    secret: SEC000000000000000000000
```
